### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Lawouach** [MrFrangipane/docgen#2]
Hi there,

A useful package but it looks like it has some problems. I installed it with `pip`:

```
$ pip install frangidoc
Collecting frangidoc
  Downloading https://files.pythonhosted.org/packages/0e/58/4f2eeb8fea6b8f941e5549520cd890d38a908c3cbd665279ca53f67ca890/frangidoc-1.3.2.tar.gz
Collecting GitPython (from frangidoc)
  Downloading https://files.pythonhosted.org/packages/88/9c/b462dddb492204417f88d538b0931e87631f2a98afe89842929f4ed9ca5b/GitPython-2.1.9-py2.py3-none-any.whl (447kB)
    100% |████████████████████████████████| 450kB 5.2MB/s 
Requirement already satisfied: PyYaml in .venvs/lib/python3.6/site-packages (from frangidoc) (3.12)
Collecting gitdb2>=2.0.0 (from GitPython->frangidoc)
  Downloading https://files.pythonhosted.org/packages/e0/95/c772c13b7c5740ec1a0924250e6defbf5dfdaee76a50d1c47f9c51f1cabb/gitdb2-2.0.3-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 8.2MB/s 
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython->frangidoc)
  Downloading https://files.pythonhosted.org/packages/e3/59/4e22f692e65f5f9271252a8e63f04ce4ad561d4e06192478ee48dfac9611/smmap2-2.0.3-py2.py3-none-any.whl
Building wheels for collected packages: frangidoc
  Running setup.py bdist_wheel for frangidoc ... done
  Stored in directory: .cache/pip/wheels/74/be/32/827774e868afd88860660f7135d3246733cb407a9f8018be8b
Successfully built frangidoc
Installing collected packages: smmap2, gitdb2, GitPython, frangidoc
Successfully installed GitPython-2.1.9 frangidoc-1.3.2 gitdb2-2.0.3 smmap2-2.0.3
```

and now I get:

```
$ python -m frangidoc module mymodule
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File ".venv/lib/python3.6/site-packages/frangidoc/__init__.py", line 1, in <module>
    from api import *
ModuleNotFoundError: No module named 'api'
```

**Comment by MrFrangipane** [comment]
This issue duplicates with #3 : import errors are due to relative python2 imports
